service: email-piping-service

frameworkVersion: ">=1.1.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  processemail:
    handler: handler.processemail
  processacceptreject:
    handler: handler.processacceptreject

resources:
  Resources:
    GiveSESPermissionToInvokeProcessemailLambdaFunction:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: { "Fn::GetAtt": [ "ProcessemailLambdaFunction", "Arn" ] }
        Principal: ses.amazonaws.com
        Action: 'lambda:InvokeFunction'
        SourceAccount: { Ref: AWS::AccountId }
    GiveSESPermissionToInvokeProcessacceptrejectLambdaFunction:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: { "Fn::GetAtt": [ "ProcessacceptrejectLambdaFunction", "Arn" ] }
        Principal: ses.amazonaws.com
        Action: 'lambda:InvokeFunction'
        SourceAccount: { Ref: AWS::AccountId }